name: generate-snake-game-from-github-contribution-grid

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: "BeatrizBastosBorges"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/dark.svg?palette=github-dark&color_snake=blue
            dist/light.svg?color_snake=#7845ab
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dist/*
          git commit -m "chore: Update snake game images" || echo "No changes to commit"
          git push
